### PR TITLE
Update org.kyrogenix.Pick runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Also update appdata to fix appstreamcli warnings.

### CODE REVIEW

**Comment by ghost** [comment]
@stuartlangridge I've updated org.kyrogenix.Pick runtime 42 to 46 due to it was out-of-date and EOL.

**Comment by stuartlangridge** [comment]
> @stuartlangridge I've updated org.kyrogenix.Pick runtime 42 to 46 due to it was out-of-date and EOL.

I see that! What do I need to do to make use of this?

**Comment by ghost** [comment]
I think you can merge the pull request if it looks okay to you.

I'm relatively new to packaging Linux apps. You might want to consult the community (https://discourse.flathub.org/) or someone more experienced than me.

**Comment by stuartlangridge** [comment]
I can certainly merge it, and I'm happy to do so, but I'm not sure whether I need to do anything else to make flathub know or care that I've done so :) I'll try to look into that when I have time.

**Comment by ghost** [comment]
You might need to give some commands. I don't know.

https://github.com/flathub/org.gnome.Robots/pull/6

**Comment by ghost** [comment]
@barthalion I updated the Pick runtime to 46.

Could you test it.

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
I assume this only works with X11 sessions?

**Comment by stuartlangridge** [comment]
> I assume this only works with X11 sessions?

That's correct. It's not clear whether it's even possible to work on Wayland without there being a standard API to ask the compositor (whichever one it is) for a screenshot of an area, and there isn't such an API (and implementing it would be a bunch of testing work that I'm not in a position to do anyway). So Pick is X only for now.

**Pull request merged**
